# Generated by Django 2.2.3 on 2019-07-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('deliveryTime', models.IntegerField(verbose_name='送达时间')),
                ('score', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='评分')),
                ('serviceScore', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='服务评分')),
                ('foodScore', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='食品评分')),
                ('rankRate', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='好评率')),
                ('minPrice', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='最低配送金额')),
                ('deliveryPrice', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='配送费')),
                ('ratingCount', models.IntegerField(verbose_name='评论数')),
                ('sellCount', models.IntegerField(verbose_name='成交量')),
                ('bulletin', models.TextField(verbose_name='公告')),
                ('avatar', models.ImageField(upload_to='', verbose_name='头像')),
                ('pics', models.TextField(verbose_name='商家图片')),
                ('infos', models.TextField(verbose_name='商家营业信息')),
                ('supports', models.TextField(verbose_name='商家优惠信息')),
            ],
            options={
                'db_table': 'seller',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
