# Generated by Django 2.2.3 on 2019-07-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_auto_20190729_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellermodel',
            name='deliveryPrice',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='配送费'),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='foodScore',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='食品评分'),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='minPrice',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='最低配送金额'),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='rankRate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='好评率'),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='serviceScore',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='服务评分'),
        ),
    ]
