# Generated by Django 2.2.3 on 2019-07-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_auto_20190729_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellermodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/avatar/%Y/%m/', verbose_name='头像'),
        ),
    ]
